-- _______________SET AUTOCOMMIT MODE ON___________________________

-- drop database
DROP DATABASE IF EXISTS health;
-- database creation
CREATE DATABASE health;

-- _______________CONNECT TO THE DATABASE__________________________
-- _______________TRANSACTION MODE MANUAL\AUTOCOMMIT_______________ 

-- drop default schema
DROP SCHEMA IF EXISTS public;

DROP SCHEMA IF EXISTS hms CASCADE;
-- create new schema health_management_system (hms)
CREATE SCHEMA hms;

-- _______________SELECT HMS SCHEMA FOR OBJECTS____________

-- set the search path (if there are any other schemas)
SET search_path = institutions;

-- _______________TABLES DEFINITION_______________

CREATE TABLE IF NOT EXISTS hms.street (
    street_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street_name VARCHAR(50) NOT NULL UNIQUE
 );

CREATE TABLE IF NOT EXISTS hms.district (
    district_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_name VARCHAR(50) NOT NULL UNIQUE
 );


CREATE TABLE IF NOT EXISTS hms.street_by_district (
    district_id INTEGER NOT NULL REFERENCES hms.district (district_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    street_id INTEGER NOT NULL REFERENCES hms.street (street_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (district_id, street_id)
 );


CREATE TABLE IF NOT EXISTS hms.locations (
    location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_id INTEGER NOT NULL REFERENCES hms.district (district_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    street_id INTEGER NOT NULL REFERENCES hms.street (street_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    building_number VARCHAR(10),
    premise VARCHAR(10),
    update_ts TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS hms.patients (
    patient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INTEGER NOT NULL REFERENCES hms.locations (location_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    surname VARCHAR(50) NOT NULL,
    given_name VARCHAR(50),
    fullname VARCHAR(101) GENERATED ALWAYS AS (given_name || ' ' || surname) STORED,
    gender VARCHAR(7),
    birth_date DATE CONSTRAINT wrong_dob CHECK (birth_date BETWEEN DATE '1930-01-01' AND NOW()),
    phone VARCHAR(15) NOT NULL,
    update_ts TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT wrong_gender CHECK (gender IN ('MALE', 'FEMALE', 'OTHERS'))
);

CREATE TABLE IF NOT EXISTS hms.insurance (
	insurance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	patient_id INTEGER NOT NULL REFERENCES hms.patients (patient_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	policy_number INTEGER NOT NULL UNIQUE,
	company_name VARCHAR(50) NOT NULL,
	effective_date DATE,
	expired_date DATE,
	total_amount DECIMAL(10,2) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	update_ts TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	CONSTRAINT expired_date_check CHECK (expired_date > effective_date)
);
CREATE TABLE IF NOT EXISTS hms.hospitals (
	hospital_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE,
	location_id INTEGER NOT NULL REFERENCES hms.locations (location_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	capacity INTEGER NOT NULL,
	phone VARCHAR(15) NOT NULL,
	email VARCHAR(255) NOT NULL ,
	website VARCHAR(2083),
	update_ts TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	CONSTRAINT email_pattern CHECK (email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,}$'),
	CONSTRAINT non_negative_capacity CHECK (capacity >= 0)
);

CREATE TABLE IF NOT EXISTS hms.staff (
    staff_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- let's suppose that staff member may work only in one institution at a time
    hospital_id INTEGER NOT NULL REFERENCES hms.hospitals (hospital_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    surname VARCHAR(50) NOT NULL,
    given_name VARCHAR(50),
    fullname VARCHAR(101) GENERATED ALWAYS AS (given_name || ' ' || surname) STORED,
    role VARCHAR(50),
    birth_date DATE,
    phone VARCHAR(15) NOT NULL,
    update_ts TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT wrong_dob CHECK (birth_date BETWEEN DATE '1930-01-01' AND NOW())
);

CREATE TABLE IF NOT EXISTS hms.appointments (
    appointment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES hms.patients (patient_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    staff_id INTEGER REFERENCES hms.staff (staff_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    appointment_dt TIMESTAMP NOT NULL,
    description TEXT,
	CONSTRAINT future_appointment_date CHECK (appointment_dt <= NOW()),
	-- time must be between 9 and 17
	CONSTRAINT valid_appointment_time CHECK (EXTRACT(HOUR FROM appointment_dt) >= 9 AND EXTRACT(HOUR FROM appointment_dt) <= 17)
);

CREATE TABLE IF NOT EXISTS hms.services (
	service_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	service_name VARCHAR(255) NOT NULL UNIQUE,
	service_description TEXT,
	update_ts TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS hms.billings (
	billing_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	patient_id INTEGER NOT NULL REFERENCES hms.patients (patient_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	appointment_id INTEGER NOT NULL REFERENCES hms.appointments (appointment_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	service_id INTEGER NOT NULL REFERENCES hms.services (service_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	amount DECIMAL(10,2) NOT NULL,
	billing_date TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT amount_not_null CHECK (amount > 0)
);

-- __________________________________________INSERTION PART__________________________________________

INSERT INTO hms.street (street_name)
VALUES
('MAIN STREET'),
('PARK AVENUE'),
('OAK STREET'),
('MAPLE AVENUE'),
('ELM STREET'),
('PINE STREET'),
('WILLOW AVENUE'),
('CEDAR STREET'),
('WALNUT STREET'),
('BIRCH AVENUE')
ON CONFLICT ON CONSTRAINT street_street_name_key DO NOTHING;

INSERT INTO hms.district (district_name)
VALUES
('DOWNTOWN'),
('MIDTOWN'),
('UPTOWN'),
('EAST SIDE'),
('WEST SIDE')
ON CONFLICT ON CONSTRAINT district_district_name_key DO NOTHING;

INSERT INTO hms.street_by_district (district_id, street_id)
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'DOWNTOWN'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'MAIN STREET')
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'MIDTOWN'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'PARK AVENUE')
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'UPTOWN'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'OAK STREET')
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'EAST SIDE'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'MAPLE AVENUE')
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'WEST SIDE'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'ELM STREET')
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'DOWNTOWN'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'PINE STREET')
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'MIDTOWN'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'WILLOW AVENUE')
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'UPTOWN'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'CEDAR STREET')
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'EAST SIDE'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'WALNUT STREET')   
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'WEST SIDE'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'BIRCH AVENUE') 
ON CONFLICT ON CONSTRAINT street_by_district_pkey DO NOTHING;

INSERT INTO hms.locations (district_id, street_id, building_number, premise)
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'DOWNTOWN'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'MAIN STREET'),
	   '1', NULL
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'MIDTOWN'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'PARK AVENUE'),
	   '2', NULL
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'UPTOWN'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'OAK STREET'),
	   '3', NULL
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'EAST SIDE'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'MAPLE AVENUE'),
	   '4', NULL
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'WEST SIDE'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'ELM STREET'),
	   '5', NULL
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'DOWNTOWN'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'PINE STREET'),
	   '666', 'A'
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'MIDTOWN'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'WILLOW AVENUE'),
	   '747', 'B'
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'UPTOWN'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'CEDAR STREET'),
	   '848', 'C'
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'EAST SIDE'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'WALNUT STREET'),
	   '959', 'D'
UNION
SELECT (SELECT district_id FROM hms.district WHERE district_name = 'WEST SIDE'),
	   (SELECT street_id FROM hms.street WHERE street_name = 'BIRCH AVENUE'),
	   '1012', 'E';

INSERT INTO hms.hospitals (name, location_id, capacity, phone, email, website)
SELECT 'GENERAL HOSPITAL', 
	   (SELECT location_id FROM hms.locations WHERE district_id = (SELECT district_id FROM hms.district WHERE district_name = 'DOWNTOWN') AND 
											 		street_id = (SELECT street_id FROM hms.street WHERE street_name = 'MAIN STREET')), 
		500, 
		'555-555-5555', 
		'GENERALHOSPITAL@GMAIL.COM', 
		'WWW.GENERALHOSPITAL.COM'
UNION
SELECT 'CHILDREN''S HOSPITAL', 
	   (SELECT location_id FROM hms.locations WHERE district_id = (SELECT district_id FROM hms.district WHERE district_name = 'MIDTOWN') AND 
	   												street_id = (SELECT street_id FROM hms.street WHERE street_name = 'PARK AVENUE')), 
	    300, 
	    '555-555-5556', 
	    'CHILDRENSHOSPITAL@GMAIL.COM', 
	    'WWW.CHILDRENSHOSPITAL.COM'
UNION
SELECT 'COMMUNITY HOSPITAL', 
	   (SELECT location_id FROM hms.locations WHERE district_id = (SELECT district_id FROM hms.district WHERE district_name = 'UPTOWN') AND 
	   												street_id = (SELECT street_id FROM hms.street WHERE street_name = 'OAK STREET')), 
	   400, 
	   '555-555-5557', 
	   'COMMUNITYHOSPITAL@GMAIL.COM', 
	   'WWW.COMMUNITYHOSPITAL.COM'
UNION
SELECT 'WOMEN''S HOSPITAL', 
	   (SELECT location_id FROM hms.locations WHERE district_id = (SELECT district_id FROM hms.district WHERE district_name = 'EAST SIDE') AND 
	   												street_id = (SELECT street_id FROM hms.street WHERE street_name = 'MAPLE AVENUE')), 
	   250, 
	   '555-555-5558', 
	   'WOMENSHOSPITAL@GMAIL.COM', 
	   'WWW.WOMENSHOSPITAL.COM'
UNION
SELECT 'MENTAL HEALTH HOSPITAL', 
	   (SELECT location_id FROM hms.locations WHERE district_id = (SELECT district_id FROM hms.district WHERE district_name = 'WEST SIDE') AND 
	  										        street_id = (SELECT street_id FROM hms.street WHERE street_name = 'ELM STREET')), 
	   150, 
	   '555-555-5559', 
	   'MENTALHEALTHHOSPITAL@GMAIL.COM', 
	   'WWW.MENTALHEALTHHOSPITAL.COM'
ON CONFLICT	ON CONSTRAINT hospitals_name_key DO NOTHING;

WITH inserted_data AS (
SELECT  (SELECT hospital_id FROM hms.hospitals WHERE name = 'GENERAL HOSPITAL') AS hospital_id,
		'SMITH' AS surname,
		'JOHNATHAN' AS given_name,
		'PHYSICIAN' AS role,
		DATE '1970-01-01' AS birth_date,
		'555-555-5535' AS phone
UNION
SELECT  (SELECT hospital_id FROM hms.hospitals WHERE name = 'CHILDREN''S HOSPITAL') AS hospital_id,
		'JONES' AS surname,
		'SAMANTA' AS given_name,
		'NURSE' AS role,
		DATE '1980-01-01' AS birth_date,
		'555-525-5556' AS phone
UNION
SELECT  (SELECT hospital_id FROM hms.hospitals WHERE name = 'COMMUNITY HOSPITAL') AS hospital_id,
		'BROWN' AS surname,
		'JASON' AS given_name,
		'PHYSICAL THERAPIST' AS role,
		DATE '1990-01-01' AS birth_date,
		'555-515-5557' AS phone
UNION
SELECT  (SELECT hospital_id FROM hms.hospitals WHERE name = 'WOMEN''S HOSPITAL') AS hospital_id,
		'GARCIA' AS surname,
		'KAREN' AS given_name,
		'PHYSICAL THERAPIST' AS role,
		DATE '2000-01-01' AS birth_date,
		'525-555-5558' AS phone
UNION
SELECT  (SELECT hospital_id FROM hms.hospitals WHERE name = 'MENTAL HEALTH HOSPITAL') AS hospital_id,
		'WILSON' AS surname,
		'TIM' AS given_name,
		'RADIOLOGIST' AS role,
		DATE '2010-01-01' AS birth_date,
		'555-235-5559' AS phone
)
INSERT INTO hms.staff (hospital_id, surname, given_name, role, birth_date, phone)
SELECT hospital_id, surname, given_name, role, birth_date, phone
FROM inserted_data
WHERE NOT EXISTS (SELECT 1 FROM hms.staff WHERE hospital_id = inserted_data.hospital_id AND 
												surname = inserted_data.surname AND 
												given_name = inserted_data.given_name);

WITH inserted_patients AS (
		SELECT (SELECT location_id FROM hms.locations WHERE street_id = (SELECT street_id FROM hms.street WHERE street_name = 'PINE STREET') AND 
															building_number = '666' AND 
															premise = 'A') AS location_id,
				'SMITH' AS surname, 
				'JOHN'AS given_name, 
				'MALE' AS gender, 
				DATE '1980-01-01' AS birth_date, 
				'555-555-1234' AS phone
		UNION
		SELECT (SELECT location_id FROM hms.locations WHERE street_id = (SELECT street_id FROM hms.street WHERE street_name = 'WILLOW AVENUE') AND 
															building_number = '747' AND 
															premise = 'B'),
				'JOHNSON', 'JENNY', 'FEMALE', DATE '1990-02-02', '555-555-5678'
		UNION
		SELECT (SELECT location_id FROM hms.locations WHERE street_id = (SELECT street_id FROM hms.street WHERE street_name = 'CEDAR STREET') AND 
															building_number = '848' AND 
															premise = 'C'),
				'BROWN', 'JACK', 'MALE', DATE '1985-03-03', '555-555-9101'
		UNION
		SELECT (SELECT location_id FROM hms.locations WHERE street_id = (SELECT street_id FROM hms.street WHERE street_name = 'WALNUT STREET') AND 
															building_number = '959' AND 
															premise = 'D'),
				'JOHNSON', 'SARA', 'FEMALE', DATE '1985-02-14', '523-555-1234'
		UNION
		SELECT (SELECT location_id FROM hms.locations WHERE street_id = (SELECT street_id FROM hms.street WHERE street_name = 'BIRCH AVENUE') AND 
															building_number = '1012' AND 
															premise = 'E'),
				'JOHNSON', 'MARK', 'MALE', DATE '1980-02-14', '523-455-1234')
INSERT INTO hms.patients (location_id, surname, given_name, gender, birth_date, phone)
		SELECT location_id, surname, given_name, gender, birth_date, phone
		FROM inserted_patients
		WHERE NOT EXISTS (SELECT 1 FROM hms.patients WHERE location_id = inserted_patients.location_id AND 
														   surname = inserted_patients.surname AND 
														   given_name = inserted_patients.given_name);

INSERT INTO hms.insurance (patient_id, policy_number, company_name, effective_date, expired_date, total_amount, is_active) 
	   SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JOHN SMITH'),
	   		  43673767, 'ABC INSURANCE', DATE '2022-01-01', DATE '2023-12-31', 1550, TRUE
	   UNION
	   SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JENNY JOHNSON'),
	   		  43673761, 'DEF INSURANCE', DATE '2022-03-01', DATE '2023-12-31', 2560, TRUE
	   UNION
	   SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JACK BROWN'),
	   		  43673762, 'GHI INSURANCE', DATE '2022-04-01', DATE '2023-10-31', 3820, TRUE
	   UNION
	   SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'SARA JOHNSON'),
	   		  43673763, 'JKL INSURANCE', DATE '2022-05-01', DATE '2023-09-30', 24356, TRUE
	   UNION
	   SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'MARK JOHNSON'),
	   		  43673764, 'MNO INSURANCE', DATE '2022-06-01', DATE '2023-08-31', 890, TRUE
ON CONFLICT	ON CONSTRAINT insurance_policy_number_key DO NOTHING;

INSERT INTO hms.services (service_name, service_description) VALUES 
		('ANNUAL PHYSICAL EXAMINATION', 'A FULL PHYSICAL EXAMINATION AND DIAGNOSTIC TESTS TO ASSESS OVERALL HEALTH'),
		('HYPERTENSION MANAGEMENT', 'A FOLLOW-UP APPOINTMENT WITH A HEALTHCARE PROVIDER TO REVIEW THE PROGRESS OF HYPERTENSION MANAGEMENT, INCLUDING MONITORING OF BLOOD PRESSURE, MEDICATION ADJUSTMENTS, AND LIFESTYLE CHANGES.'),
		('JOINT PAIN CONSULTATION', 'A CONSULTATION WITH A SPECIALIST TO EVALUATE AND DIAGNOSE PAIN, INCLUDING A PHYSICAL EXAMINATION AND ANY NECESSARY IMAGING TESTS.'),
		('VACCINATIONS', 'ADMINISTERING VACCINATIONS TO PROTECT AGAINST VARIOUS DISEASES'),
		('X-RAY', 'RADIOGRAPHIC IMAGING TO DIAGNOSE AND MONITOR VARIOUS MEDICAL CONDITIONS'),
		('BLOOD TEST', 'A DIAGNOSTIC TEST TO MEASURE THE PRESENCE AND/OR CONCENTRATION OF VARIOUS SUBSTANCES IN THE BLOOD'),
		('PHYSICAL THERAPY', 'TREATMENT TO ALLEVIATE PAIN, IMPROVE MOBILITY, AND ENHANCE RECOVERY FROM INJURIES OR SURGERIES')
ON CONFLICT	ON CONSTRAINT services_service_name_key DO NOTHING;

INSERT INTO hms.appointments (patient_id, staff_id, appointment_dt, description)
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JOHN SMITH'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'JOHNATHAN SMITH'),
			   TIMESTAMP '2023-01-05 10:00:00',
			   'FOLLOW-UP APPOINTMENT FOR HYPERTENSION MANAGEMENT'
	    UNION
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JOHN SMITH'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'JOHNATHAN SMITH'),
			   TIMESTAMP '2023-01-20 10:00:00',
			   'ANNUAL PHYSICAL EXAMINATION'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JOHN SMITH'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'JOHNATHAN SMITH'),
			   TIMESTAMP '2023-01-16 15:30:00',
			   'CONSULTATION FOR KNEE PAIN'	
				UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JENNY JOHNSON'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'JOHNATHAN SMITH'),
			   TIMESTAMP '2023-01-16 16:30:00',
			   'FOLLOW-UP APPOINTMENT FOR HYPERTENSION MANAGEMENT'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JENNY JOHNSON'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'JOHNATHAN SMITH'),
			   TIMESTAMP '2023-01-17 15:30:00',
			   'ANNUAL PHYSICAL EXAMINATION'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JOHN SMITH'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'SAMANTA JONES'),
			   TIMESTAMP '2023-01-03 09:30:00',
			   'FLU VACCINATION'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JENNY JOHNSON'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'SAMANTA JONES'),
			   TIMESTAMP '2023-01-20 09:30:00',
			   'CHICKENPOX VACCINATION'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JOHN SMITH'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'SAMANTA JONES'),
			   TIMESTAMP '2023-01-21 11:30:00',
			   'BLOOD TEST'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JENNY JOHNSON'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'SAMANTA JONES'),
			   TIMESTAMP '2023-01-21 11:00:00',
			   'BLOOD TEST'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JACK BROWN'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'SAMANTA JONES'),
			   TIMESTAMP '2023-01-25 09:30:00',
			   'FLU VACCINATION'		   
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JACK BROWN'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'KAREN GARCIA'),
			   TIMESTAMP '2023-01-08 09:30:00',
			   'PHYSICAL THERAPY SESSION FOR REHABILITATION AFTER KNEE SURGERY'	
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'SARA JOHNSON'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'TIM WILSON'),
			   TIMESTAMP '2023-01-09 09:30:00',
			   'RADIOLOGIST APPOINTMENT FOR X-RAY AND MRI OF SHOULDER JOINT'	
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'MARK JOHNSON'),
			   (SELECT staff_id FROM hms.staff WHERE fullname = 'JASON BROWN'),
			   TIMESTAMP '2023-01-10 09:30:00',
			   'PHYSICAL THERAPY SESSION FOR BACK PAIN MANAGEMENT AND STRENGTHENING';	
			  
INSERT INTO hms.billings (patient_id, appointment_id, service_id, amount, billing_date)
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'MARK JOHNSON'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-10 09:30:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'PHYSICAL THERAPY'),
			   100.00,
			   TIMESTAMP WITH TIME ZONE '2023-01-10 10:30:00'
	 	UNION
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'SARA JOHNSON'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-09 09:30:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'X-RAY'),
			   125.00,
			   TIMESTAMP WITH TIME ZONE '2023-01-09 10:30:00'
	 	UNION	 	
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JACK BROWN'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-08 09:30:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'PHYSICAL THERAPY'),
			   100.00,
			   TIMESTAMP WITH TIME ZONE '2023-01-08 10:30:00'
	 	UNION			
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JACK BROWN'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-25 09:30:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'VACCINATIONS'),
			   50.00,
			   TIMESTAMP WITH TIME ZONE '2023-01-25 10:30:00'
	 	UNION
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JENNY JOHNSON'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-21 11:00:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'BLOOD TEST'),
			   30.00,
			   TIMESTAMP WITH TIME ZONE '2023-01-21 11:30:00'
	 	UNION	 
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JOHN SMITH'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-21 11:30:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'BLOOD TEST'),
			   30.00,
			   TIMESTAMP WITH TIME ZONE '2023-01-21 12:30:00'
	 	UNION	 	 	
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JENNY JOHNSON'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-20 09:30:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'VACCINATIONS'),
			   50.00,
			   TIMESTAMP WITH TIME ZONE '2023-01-20 10:30:00'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JOHN SMITH'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-03 09:30:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'VACCINATIONS'),
			   50.00,   
			   TIMESTAMP WITH TIME ZONE '2023-01-03 10:30:00'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JENNY JOHNSON'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-17 15:30:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'ANNUAL PHYSICAL EXAMINATION'),
			   150.00,
			   TIMESTAMP WITH TIME ZONE '2023-01-17 16:30:00'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JENNY JOHNSON'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-16 16:30:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'HYPERTENSION MANAGEMENT'),
			   170.00,
			   TIMESTAMP WITH TIME ZONE '2023-01-16 17:30:00'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JOHN SMITH'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-16 15:30:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'JOINT PAIN CONSULTATION'),
			   90.00,
			   TIMESTAMP WITH TIME ZONE '2023-01-16 16:30:00'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JOHN SMITH'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-20 10:00:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'ANNUAL PHYSICAL EXAMINATION'),
			   150.00,
			   TIMESTAMP WITH TIME ZONE '2023-01-20 10:30:00'
		UNION	   
		SELECT (SELECT patient_id FROM hms.patients WHERE fullname = 'JOHN SMITH'),
			   (SELECT appointment_id FROM hms.appointments WHERE appointment_dt = TIMESTAMP '2023-01-05 10:00:00'),
			   (SELECT service_id FROM hms.services WHERE service_name = 'HYPERTENSION MANAGEMENT'),
			   170.00,
			   TIMESTAMP WITH TIME ZONE '2023-01-05 11:30:00';			  
			  
-- a query to identify doctors with insufficient workload (less than 5 patients a month for the past few months)
SELECT staff.fullname
FROM   hms.staff
-- join staff info with appointments
       INNER JOIN hms.appointments
               ON staff.staff_id = appointments.staff_id
-- select only doctors               
WHERE  staff.role != 'NURSE' AND
-- specify date period (from January 1st to current date)
       appointments.appointment_dt BETWEEN '2023-01-01' AND CURRENT_DATE
-- group by unique field       
GROUP  BY staff.staff_id,
          staff.fullname
-- filter doctors with less than 5 patients in January          
HAVING COUNT(appointments.staff_id) < 5
ORDER BY staff.fullname; 